# AskNameOfAI Intent
---
type: intent
name: askNameOfAI
utterances:
  - what is your name?
  - what do i call you?
  - what are you named as?
  - who are you?

# greet Intent
---
type: intent
name: greet
utterances:
  - hello
  - hi
  - how are you doing?
  - whats up?
