# AskNameOfAI Intent
---
type: intent
name: AskNameOfAI
utterances:
  - what is your name?
  - what do i call you?
  - what are you named as?
  - who are you?

# Greet Intent
---
type: intent
name: Greet
utterances:
  - hello
  - hi
  - howdy
  - how are you doing?
  - whats up?

# GreetWithName Intent
---
type: intent
name: GreetWithName
slots:
  - name: name
    entity: name
utterances:
  - hi, my name is [name](Anish)
  - hello, i am [name](Shreya)
  - im [name](Shriyu), who are you?
